name = "qualitour-astro"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public", "disable_nodejs_process_v2"]
pages_build_output_dir = "./dist"

[observability]
enabled = true
